data_loader:
  name: "T_Less"
  input_size: 224
  config:
    dataset_path: "datasets/t-less_v2"
    dirs: ["train_kinect/01", "train_kinect/02", "train_kinect/03", "train_kinect/04", "train_kinect/05",
           "train_kinect/06", "train_kinect/07", "train_kinect/08", "train_kinect/09",
           "train_kinect/10", "train_kinect/11", "train_kinect/12", "train_kinect/13", "train_kinect/14",
           "train_kinect/15", "train_kinect/16", "train_kinect/17", "train_kinect/18", "train_kinect/19",
           "train_kinect/20", "train_kinect/21", "train_kinect/22", "train_kinect/23", "train_kinect/24", "train_kinect/25",
           "train_kinect/26", "train_kinect/27", "train_kinect/28", "train_kinect/29", "train_kinect/30"]
    hdf5: "tless.hdf5"
    biterion: False
    blur: True
train:
  loss_function: "bingham" # deepvo_mse, deepvo_prob, deepvo_bingham_fixed_z, deepvo_bingham
  loss_parameters:
    lookup_table_file: "precomputed/lookup_-500_0_40.dill"
    orthogonalization: "gram_schmidt"
  device: "cuda:0"
  num_outputs: 19
  num_epochs: 5
  num_channels: 3
  batch_size: 32
  learning_rate: 0.0001
  model: "resnet18"
  save_as: "tless/bd_5_blur"
  save_dir: "models/tless/bd_5_blur"
  resume: False
