data_loader:
  name: "T_Less"
  input_size: 224
  config:
     dataset_path: "datasets/t-less_v2"
     hdf5: "tless.hdf5"
     biterion: True
     blur: False
train:
  loss_function: "von_mises"
  device: "cuda:0"
  num_outputs: 9 
  num_epochs: 5
  num_channels: 3
  batch_size: 32 
  learning_rate: 0.0001
  model: "resnet18"
  save_as: "tless/vm_5"
  save_dir: "models/tless/vm_5"
  resume: False
